// Generated by HumanScript Compiler

#include <iostream>
#include <algorithm>

#include <iomanip>  // For std::boolalpha with 'says'
#include <string>   // For std::to_string with 'says'

int main() {
    std::cout << std::boolalpha; // Print booleans as true/false
    long long age = 18LL;
    long long khangage = 10LL;
    std::cout << ((age == khangage)) << std::endl;
    return 0;
}
